### PR TITLE
Result ordering

### PR DESCRIPTION
**Pull request by ghost**
This is more a feature request than a pull request actually, since I'm really not sure it's the right way to do it. It just seems to work for my use case. 

Cheers,
Alex

### CODE REVIEW

**Comment by TonyGen** [comment]
Hi Alex,

Thanks for the request. I considered doing this but I figured 6 args was getting out of hand and the user can add orderby to the selector himself.

**Comment by ghost** [comment]
Hi Tony,

OK, at the time I couldn't figure out how to add orderby to the selector. Now that you're saying it is possible, I'll have another go with more confidence. 

Thanks!

**Comment by TonyGen** [comment]
You did it yourself in your change. The user would just do it himself: find(Collection, {'query', Selector, orderby, OrderBy})

**Comment by ghost** [comment]
Right, it does work indeed. I feel a bit stupid now but thanks a lot! :-)

**Pull request closed without merging**
