### PR TITLE
Multiple fixes and additions.

### PR DESCRIPTION
**Pull request by soplakanets**
Major chanages:
- Added Makefile for ease of use.
- Makefile also simplifies build process (dependencies are resolved with rebar).
- Fixed doc comments in src/mongo.erl so edoc does not fail with errors.

### CODE REVIEW

**Comment by superbobry** [comment]
`Makefile`, why, really?

**Comment by soplakanets** [comment]
@superbobry I am not sure what you mean. If you're asking why make and not X - answer is simple, because everybody has it installed. 
I am not a fan of make neither, but, not sure introducing another build tool is a good idea.

Anyways, I am up for suggestions, have no strong feelings for make :) Let's let maintainer decide.

**Comment by superbobry** [comment]
Well, I'm not very familiar with Erlang environment, but it looks like most of the folks just use `rebar` for everything; this includes tests (which seem to be the only two _long_ lines in the `Makefile` you've written).

**Comment by soplakanets** [comment]
@superbobry My opinion:
1. As I said -- it's a matter of personal preference. I personally hate typing `rebar get-deps compile` if I can shorten it to `make`. 
2. Unfortunately tests in a current form can not be run with rebar. Check source code.
3. Most of the projects _I_ saw use rebar+Makefiles, including [Webmachine](https://github.com/basho/webmachine/blob/master/Makefile), which is a product of a company behind rebar :)

**Comment by TonyGen** [comment]
Hi guys, this TonyGen site is no longer the master for mongodb-erlang, mongodb is. Can you please post there. Thanks, Tony

**Comment by superbobry** [comment]
Sure, but mongodb's repository has no issues enabled.

**Comment by TonyGen** [comment]
Mongo tracks issues at jira.mongodb.org. Select Erlang project.

**Pull request closed without merging**
